#!/bin/sh

# This script requires the msession script in order to receive a moodle session token
# The first argument is the user-id

echo -n "$1: "
COURSES=$(curl "https://moodle2.leibniz-gymnasium-oestringen.de/moodle/user/profile.php?id=$1&showallcourses=1" \
  -H 'User-Agent: ' --silent \
  -H "Cookie: MoodleSession=$(msession)" \
  | grep Kursprofil | sed -E "s/<\/li><li>/\n/g;" | sed -E 's/^<a.+?course=//g;s/\&amp;showallcourses=1\">/;/g;s/<\/a>//g;s/<.+>//g;s/\s+<a.+?course=//')

while IFS= read -r c
do
  ID=$(echo $c | awk -F";" '{ print $1 }')
  COURSE=$(echo $c | awk -F";" '{ print $2 }')

  FACH=$(echo $COURSE | awk -F"-" '{ print $1 }' | xargs)
  KLASSE=$(echo $COURSE | awk -F"-" '{ print $2 }' | xargs)
  LEHRER=$(echo $COURSE | awk -F"-" '{ print $3 }' | xargs)
  JAHR=$(echo $COURSE | awk -F"-" '{ print $4 }' | xargs)

  echo -e "\nSchueler:$1;Kurs-ID: $ID;Fach: $FACH;Klasse: $KLASSE;Lehrer:$LEHRER;Jahr: $JAHR"

# remember the course names
doas mysql -p moodle -u root --password="" << EOF
 INSERT INTO courses VALUES ($ID, "$FACH", "$KLASSE", "$LEHRER", "$JAHR");
EOF

done <<< "$COURSES"
