#!/bin/sh

ID=$(doas mysql -A -p moodle -u root --password="" <<< "SELECT name,id FROM users WHERE name LIKE \"%$1%\"" | tail -n +2)

while IFS= read -r c
do
  U_NAME=$(echo $c | awk '{ print $1 " " $2 }')
  U_ID=$(echo $c | awk '{ print $NF }')
  echo -ne "$U_ID"
  if [ -z "$2" ]; then
	echo ";$U_NAME"
  else
	  exit 0;
  fi
done <<< "$ID"
